name: Snyk
description: Runs vulnerability scans on dependencies and docker images
author: https://github.com/seek-oss
requirements:
  - docker
configuration:
  properties:
    severity:
      type: string
    org:
      type: string
  required:
    - org
    - severity
